services:
  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: test_db
    command: [ 'postgres', '-c', 'wal_level=logical' ]
    healthcheck:
      test: [ 'CMD', 'psql', '-U', 'postgres', '-c', 'SELECT 1' ]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: 'clickhouse/clickhouse-server:24.3.3.102'
    container_name: clickhouse
    volumes:
      - ./clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '8123:8123'
      - '9004:9004'
      - '9000:9000'
